projects:
  - title: Manuale OpenAgenda
    short-name: MOA
    description: |
      Manuale di utilizzo del sistema OpenAgenda per la pubblicazione di Eventi 
    website: https://www.opencontent.it/Per-la-PA/OpenAgenda
    documents:
      - title: Manuale OpenAgenda
        repository: 
      

