publisher:
  name: Opencontent Scarl
  short-name: Opencontent
  description: |
    Opencontent offre metodologie e strumenti tecnologici che semplificano 
    la vita a chi si occupa di content management e consentono di estrarre il massimo valore dai dati; 
    persegue un business model basato sull'Open Source, puntando su innovazione ed efficienza.
  website: https://www.opencontent.it/
  assets:
    logo: 
